apiVersion: v1
kind: Service
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  ports:
  - port: 8086
  selector:
    app: java-app
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: java-app
        tier: frontend
    spec:
      containers:
      - name: java-app
        image: java-example-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8086
          name: java-app
