apiVersion: v1
kind: Service
metadata:
  name: mysql-standalone
  labels:
    app: java-app
spec:
  ports:
  - port: 3306
  selector:
    app: java-app
    tier: mysql-standalone
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-standalone
  labels:
    app: java-app
spec:
  selector:
    matchLabels:
      app: java-app
      tier: mysql-standalone
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: java-app
        tier: mysql-standalone
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-standalone
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_USER
          value: sa
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password